"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const comment_controller_1 = require("../controllers/comment.controller");
const router = (0, express_1.Router)();
router.get('/post/:postId', comment_controller_1.getCommentsByPostId);
router.post('/', auth_middleware_1.authenticate, comment_controller_1.createComment);
router.delete('/:id', auth_middleware_1.authenticate, comment_controller_1.deleteComment);
router.put('/:id', auth_middleware_1.authenticate, comment_controller_1.updateComment);
exports.default = router;
