"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const isAdmin_middleware_1 = require("../middlewares/isAdmin.middleware");
const post_controller_1 = require("../controllers/post.controller");
const router = (0, express_1.Router)();
router.get('/', post_controller_1.getAllPosts);
router.get('/:id', post_controller_1.getPostById);
router.post('/', auth_middleware_1.authenticate, post_controller_1.createPost);
router.delete('/:id', auth_middleware_1.authenticate, isAdmin_middleware_1.isAdmin, post_controller_1.deletePostById);
exports.default = router;
