"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const user_controller_1 = require("../controllers/user.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const user_controller_2 = require("../controllers/user.controller");
const router = (0, express_1.Router)();
router.post('/register', user_controller_1.registerUser);
router.post('/login', user_controller_1.loginUser);
router.get('/me', auth_middleware_1.authenticate, user_controller_1.getCurrentUser);
router.get('/', user_controller_2.getAllUsers);
router.get('/logout', auth_middleware_1.authenticate, user_controller_2.logoutUser);
exports.default = router;
